apiVersion: v1
kind: Service
metadata:
  name: rickshaw-db
  labels:
    app: rickshaw
    tier: db
spec:
  ports:
    - port: 3306
  selector:
    app: rickshaw
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: rickshaw
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickshaw-db
  labels:
    app: rickshaw
spec:
  selector:
    matchLabels:
      app: rickshaw
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rickshaw
        tier: db
    spec:
      initContainers:
      - name: volume-mount-hack
        image: alpine:3.9
        command: ["/bin/sh", "-c", "chown -R 1001:1001 /var/lib/mysql"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      containers:
      - image: percona:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rickshaw-secret
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: rickshaw-config
              key: app_username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rickshaw-secret
              key: app_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: rickshaw-config
              key: app_dbname
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
