apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rickshaw-app
  namespace: monitoring
  labels:
    app: rickshaw
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: rickshaw
      tier: app
  endpoints:
  - interval: 30s
    port: http
